// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.857
package main

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Header(success bool) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<header><div class=\"scene\"><div class=\"cloud-1\"></div><div class=\"cloud-2\"></div></div></header><style scoped>\n\t\t.cloud-1 {\n\t\t\tbackground-image: url(\"/static/images/cloud-1.svg\");\n\t\t\tposition: absolute;\n\t\t\twidth: 159px;\n\t\t\theight: 92px;\n\t\t\ttop: 50px;\n\t\t\tright: 800px;\n\t\t\tanimation: float infinite 5s ease-in;\n\t\t}\n\n\t\t.cloud-2 {\n\t\t\tbackground-image: url(\"/static/images/cloud-2.svg\");\n\t\t\tposition: absolute;\n\t\t\theight: 128px;\n\t\t\twidth: 228px;\n\t\t\tright: 500px;\n\t\t\ttop: 30px;\n\t\t\tanimation: float infinite 5s ease-in;\n\t\t}\n\n\t\t@keyframes float {\n\t\t\t0% {\n\t\t\t\ttransform: translate(0, 0);\n\t\t\t}\n\n\t\t\t50% {\n\t\t\t\ttransform: translate(7px, 0px) rotate(5deg);\n\t\t\t}\n\t\t}\n\t</style>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
